<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

### <font color="green">1.1 Challenge: Importing our Library</font>

In [21]:
# Let's import numpy
#
import numpy as np

### <font color="green">1.2 Challenge: Creating an Array</font>

In [22]:
# Challenge 1 
# Create an array of five zeros
#
zeros_array = np.zeros((5))
zeros_array

array([0., 0., 0., 0., 0.])

In [23]:
# Challenge 2
# Create an array of six ones 
#
ones_array = np.ones((6))
ones_array

array([1., 1., 1., 1., 1., 1.])

In [24]:
# Challenge 3
# Create an array of the integers from 10 to 50
#
integers_array =  np.array([x for x in range(10, 51)])
integers_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [25]:
# Challenge 4
# Create an array of odd integers from 20 to 60
#
odd_integers_array = np.array([x for x in range(20, 61) if x % 2 != 0])
odd_integers_array

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59])

In [27]:
# Challenge 5
# Create an array of 25 random numbers 
#
random_numbers_array = np.random.rand(25)
random_numbers_array

array([0.3442155 , 0.64407131, 0.91475489, 0.61120602, 0.10620614,
       0.50863794, 0.97119023, 0.86514903, 0.30347092, 0.92649453,
       0.50366378, 0.19879418, 0.61153297, 0.44583745, 0.6083169 ,
       0.56147187, 0.11831433, 0.30840324, 0.85908539, 0.87862738,
       0.86854078, 0.18559568, 0.99370696, 0.26366567, 0.83564024])

### <font color="green">1.3 Working with Matrices</font>

In [28]:
# Challenge 6
# Write code to replicate the expected matrix output 
# of the cell shown below

data = np.arange(1, 21).reshape(5, 4)
matrix_output = np.array(data)
matrix_output

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [0]:
# Challenge 6: Expected Output
# [Do not run this cell]
# The output of this cell will disappear when run

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [29]:
# Challenge 7
# Let's write code to replicate the expected matrix output 
# of the cell shown below

replicate_array = np.array([[14, 15, 16],[18, 19, 20]])
replicate_array

array([[14, 15, 16],
       [18, 19, 20]])

In [0]:
# Challenge 7: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[14 15 16]
 [18 19 20]]


In [30]:
# Challenge 8
# Let's write code to replicate the expected matrix output 
# of the cell shown below

replicate_array[1,-1]

20

In [0]:
# Challenge 8: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

20

In [31]:
# Challenge 9
# Let's write code to replicate the expected matrix output 
# of the cell shown below

new_replicate = np.arange(13, 21).reshape(2, 4)
new_replicate

array([[13, 14, 15, 16],
       [17, 18, 19, 20]])

In [0]:
# Challenge 9: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[13 14 15 16]
 [17 18 19 20]]


In [35]:
# Challenge 10
# Let's find out the mean of first column values 
# in our matrix in challenge 6 above
# 

col1_mean = np.mean(matrix_output[:, 0])
col1_mean

9.0

In [37]:
# Challenge 11
# Let's find out the sum of second column values 
# in our matrix in challenge 6 above
#
col2_sum = np.sum(matrix_output[:, 1])
col2_sum

50

In [54]:
# Challenge 12
# How do we find out the sum of all columns of the challenge 6 output
# The resulting array should contain the sums of each column
# 
column_sums = {}
for col in range(matrix_output.shape[1]):
    col_name = f"col_{col + 1}" 
    col_sum = np.sum(matrix_output[:, col])
    column_sums[col_name] = col_sum

for col_name, col_sum in column_sums.items():
    print(f"{col_name} : {col_sum}")

col_1 : 45
col_2 : 50
col_3 : 55
col_4 : 60


In [82]:
example = np.random.rand(100000000).reshape(1000000, 100)

def column_summation(dataframe):
    column_sums = {}
    for col in range(dataframe.shape[1]):
        col_name = f"col_{col + 1}" 
        col_sum = np.sum(dataframe[:, col])
        column_sums[col_name] = col_sum

    return column_sums


column_summation(example)

{'col_1': 499841.2659568747,
 'col_2': 500045.50494322303,
 'col_3': 499443.50253030687,
 'col_4': 499960.16456892365,
 'col_5': 499609.71733107546,
 'col_6': 500984.65452071925,
 'col_7': 500536.5151154085,
 'col_8': 499598.29245835525,
 'col_9': 500143.9705060786,
 'col_10': 499456.86458909686,
 'col_11': 500084.5975602392,
 'col_12': 500148.2137649965,
 'col_13': 499528.5777017007,
 'col_14': 499993.2192947009,
 'col_15': 499423.0411563404,
 'col_16': 500129.55913236685,
 'col_17': 499137.7494104646,
 'col_18': 500008.96900191385,
 'col_19': 499692.6099005962,
 'col_20': 499839.16671286273,
 'col_21': 500185.18374137656,
 'col_22': 499790.15553342353,
 'col_23': 499695.17931668495,
 'col_24': 499575.5400877228,
 'col_25': 499950.0105839474,
 'col_26': 500030.5950074121,
 'col_27': 499711.0707766111,
 'col_28': 499359.36039041856,
 'col_29': 499972.46236787696,
 'col_30': 500221.7325129894,
 'col_31': 499395.86369364825,
 'col_32': 500519.73227859935,
 'col_33': 499897.41487652645,
 